[package]
name = "circle-plonk-dsl-hints"
version = "0.1.0"
edition = "2021"

[dependencies]
stwo-prover.workspace = true
num-traits.workspace = true
itertools.workspace = true
log = "0.4.25"

[dev-dependencies]
bincode.workspace = true